$mainMod = SUPER
$terminal = kitty
$fileManager = thunar
$menu = wofi

# appearance and behavior
decoration {
    shadow {
        enabled = false
    }
}
general {
    border_size = 1
    gaps_in = 4
    gaps_out = 8
}
input {
    natural_scroll = true;

    touchpad {
        natural_scroll = true;
    }
}

# apps
bind = $mainMod, b, exec, pkill waybar && waybar
bind = $mainMod, e, exec, $fileManager
bind = $mainMod, q, exec, $terminal
bind = $mainMod, r, exec, pidof wofi && pkill wofi || wofi --no-actions

# system
bind = $mainMod, c, killactive,
bind = $mainMod, ESCAPE, exec, systemctl suspend
bind = $mainMod, m, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit

# display
monitor = , preferred, auto, 1.25

# function keys
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl  = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindl  = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+

bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 5%-
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set 5%+

# startup
exec-once = hyprctl dispatch workspace 1
exec-once = hyprctl dispatch workspace 2
exec-once = hyprctl dispatch workspace 3
exec-once = hyprctl dispatch workspace 4

exec-once = hyprpaper
exec-once = hyprsunset

# workspaces
workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4

bind = SUPER SHIFT, left, movetoworkspace, e-1
bind = SUPER SHIFT, right, movetoworkspace, e+1

# window management
bindel = $mainMod, down, movewindow, d
bindel = $mainMod, left, movewindow, l
bindel = $mainMod, right, movewindow, r
bindel = $mainMod, up, movewindow, u
